---
- name: Install docker on the nodes
  gather_facts: true
  become: true
  hosts: all
  vars:
    docker_users: []
    add_ansible_user_to_docker_group: true
  roles:
    - { role: ../roles/install-docker }
