---
- name: Install Kibana
  ansible.builtin.apt:
    name: kibana

- name: Enable remote access to Kibana
  ansible.builtin.replace:
    path: /etc/kibana/kibana.yml
    regexp: "^#server.host.+$"
    replace: "server.host: \"0.0.0.0\""

- name: Create Kibana Enrollment Token
  ansible.builtin.shell:
    cmd: /usr/share/elasticsearch/bin/elasticsearch-create-enrollment-token -s kibana
  register: kibana_token
  notify: Print Kibana Enrollment Token

- name: Start/Enable Kibana Systemd Service
  ansible.builtin.systemd:
    daemon-reload: true
    name: kibana
    state: started
    enabled: true
  when:
    - enable_kibana | bool
